---
title: "DEA of Tregs"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(Matrix)
library(Seurat)
library(SeuratObject)
library(dplyr)
library(ggplot2)
library(tidyverse)
library(gridExtra)
library(grid)


scanpy_export_to_seurat <- function(mtx, cells, genes) {
  data <- readMM(mtx)
  data <- t(data)
  
  cells.table <- read.table(
    cells,
    sep = '\t',
    header = TRUE,
    row.names = 1
  )
  
  genes.table <- read.table(
    genes,
    sep = '\t',
    header = TRUE,
    row.names = 1
  )
  
  colnames(data) <- rownames(cells.table)
  rownames(data) <- rownames(genes.table)
  
  obj <- CreateSeuratObject(
    counts = as.sparse(data),
    meta.data = cells.table
  )
  
  return(obj)
}
```

# Read data from files and put them into SeuratObjects
```{r}
tregs.tissue.scps <- scanpy_export_to_seurat(
  '../diffexp/tregs.tissue.scps.counts.mtx',
  '../diffexp/tregs.tissue.scps.obs.tsv',
  '../diffexp/tregs.tissue.scps.var.tsv'
)

tregs.tissue.scps.sat1 <- scanpy_export_to_seurat(
  '../diffexp/tregs.tissue.scps.sat1.counts.mtx',
  '../diffexp/tregs.tissue.scps.sat1.obs.tsv',
  '../diffexp/tregs.tissue.scps.sat1.var.tsv'
)

tregs.tissue.uc <- scanpy_export_to_seurat(
  '../diffexp/tregs.tissue.uc.X.mtx',
  '../diffexp/tregs.tissue.uc.obs.tsv',
  '../diffexp/tregs.tissue.uc.var.tsv'
)

tregs.tissue.ad <- scanpy_export_to_seurat(
  '../diffexp/tregs.tissue.ad.X.mtx',
  '../diffexp/tregs.tissue.ad.obs.tsv',
  '../diffexp/tregs.tissue.ad.var.tsv'
)

tregs.pbmc.scps <- scanpy_export_to_seurat(
  '../diffexp/tregs.pbmc.scps.X.mtx',
  '../diffexp/tregs.pbmc.scps.obs.tsv',
  '../diffexp/tregs.pbmc.scps.var.tsv'
)
tregs.tissue.sc <- scanpy_export_to_seurat(
  '../diffexp/tregs.tissue.sarcoidosis.X.mtx',
  '../diffexp/tregs.tissue.sarcoidosis.obs.tsv',
  '../diffexp/tregs.tissue.sarcoidosis.var.tsv'
)
tregs.tissue.ps <- scanpy_export_to_seurat(
  '../diffexp/tregs.tissue.psoriasis.X.mtx',
  '../diffexp/tregs.tissue.psoriasis.obs.tsv',
  '../diffexp/tregs.tissue.psoriasis.var.tsv'
)
```
```{r}
# make sat1hi/lo vs healthy objects
meta <- tregs.tissue.scps.sat1@meta.data
tregs.tissue.scps.sat1hi <- subset(
  tregs.tissue.scps.sat1,
  cells = rownames(
    meta[(meta$status == 'normal') | (meta$sat1_status_majority_vote == 'SAT1_hi'),]
  )
)
tregs.tissue.scps.sat1lo <- subset(
  tregs.tissue.scps.sat1,
  cells = rownames(
    meta[(meta$status == 'normal') | (meta$sat1_status_majority_vote == 'SAT1_lo'),]
  )
)
```

```{r}
# assign ident as healthy and disease
re.ident <- function(seurat.obj, column, old_true_id, new_true_id, new_false_id) {
  Idents(
    seurat.obj,
    cells = rownames(
      subset(
        seurat.obj@meta.data, 
        subset = endsWith(seurat.obj@meta.data[[column]], old_true_id)
      )
    )
  ) <- new_true_id
  Idents(
    seurat.obj,
    cells = rownames(
      subset(
        seurat.obj@meta.data, 
        subset = !endsWith(seurat.obj@meta.data[[column]], old_true_id)
      )
    )
  ) <- new_false_id
  return(seurat.obj)
}

tregs.tissue.scps <- re.ident(tregs.tissue.scps, 'status', 'normal', 'Healthy', 'Disease')
Idents(tregs.tissue.scps.sat1) <- tregs.tissue.scps.sat1@meta.data$sat1_status_majority_vote

# this is possible because of the way we select the data in the cell above
# where we have either healthy or SAT1hi/lo cells
# to test SAT1hi/lo against healthy we just put everything that is healthy in one bin 
# and the other then is disease SAT1hi/lo cells
tregs.tissue.scps.sat1hi <- re.ident(tregs.tissue.scps.sat1hi, 'status', 'normal', 'Healthy', 'SAT1hi')
tregs.tissue.scps.sat1lo <- re.ident(tregs.tissue.scps.sat1lo, 'status', 'normal', 'Healthy', 'SAT1lo')
tregs.tissue.ad <- re.ident(tregs.tissue.ad, 'status', 'normal', 'Healthy', 'Disease')
tregs.tissue.uc <- re.ident(tregs.tissue.uc, 'status', 'control', 'Healthy', 'Disease')
tregs.pbmc.scps <- re.ident(tregs.pbmc.scps, 'status', 'normal', 'Healthy', 'Disease')
tregs.tissue.sc <- re.ident(tregs.tissue.sc, 'status', 'normal', 'Healthy', 'Disease')
tregs.tissue.ps <- re.ident(tregs.tissue.ps, 'status', 'normal', 'Healthy', 'Disease')
```

```{r}
compute.de.genes <- function(seurat.obj, ident.1, ident.2, latent.vars = NULL) {
  # MAST requires lognorm data see https://www.bioconductor.org/packages/release/bioc/vignettes/MAST/inst/doc/MAST-interoperability.html#21_From_scater_to_MAST
  seurat.obj <- NormalizeData(
    seurat.obj,
    normalization.method = 'LogNormalize',
    scale.factor = 10000
  )
  de.genes <- FindMarkers(
    seurat.obj,
    ident.1 = ident.1,
    ident.2 = ident.2,
    assay = "RNA",
    test.use = 'MAST',
    slot = "data",
    min.pct = 0.1,
    logfc.threshold = 0,
    latent.vars = latent.vars
  )
  lfc.threshold <- 0.5
  pval.threshold <- 0.001
  de.genes['significant'] <- de.genes$p_val_adj < pval.threshold & abs(de.genes$avg_log2FC) > lfc.threshold
  de.genes['gene'] <- rownames(de.genes)
  return(de.genes)
}

tregs.tissue.scps.de.genes <- compute.de.genes(tregs.tissue.scps, 'Disease', 'Healthy')
tregs.tissue.scps.sat1.de.genes <- compute.de.genes(tregs.tissue.scps.sat1, 'SAT1_hi', 'SAT1_lo')
tregs.tissue.scps.sat1hi.de.genes <- compute.de.genes(tregs.tissue.scps.sat1hi, 'SAT1hi', 'Healthy')
tregs.tissue.scps.sat1lo.de.genes <- compute.de.genes(tregs.tissue.scps.sat1lo, 'SAT1lo', 'Healthy')
tregs.tissue.ad.de.genes <- compute.de.genes(tregs.tissue.ad, 'Disease', 'Healthy')
tregs.tissue.uc.de.genes <- compute.de.genes(tregs.tissue.uc, 'Disease', 'Healthy')
tregs.pbmc.scps.de.genes <- compute.de.genes(tregs.pbmc.scps, 'Disease', 'Healthy')
tregs.tissue.sc.de.genes <- compute.de.genes(tregs.tissue.sc, 'Disease', 'Healthy')
tregs.tissue.ps.de.genes <- compute.de.genes(tregs.tissue.ps, 'Disease', 'Healthy')
```

```{r, fig.height = 20, fig.width = 10}
library(ggrepel)
plot.volcano <- function(de.genes, title, abs.xlim = 15) {
  lfc.threshold <- 0.5
  pval.threshold <- 0.001
  g <- ggplot(
    de.genes, 
    aes(x = avg_log2FC, y = -log10(p_val_adj), color = significant)
  ) + 
  geom_point() +
  ggtitle(title) +
  geom_vline(xintercept = c(-lfc.threshold, lfc.threshold), linetype = 'dashed') + 
  geom_hline(yintercept = -log10(pval.threshold), linetype = 'dashed') +
  scale_x_continuous(limits = c(-abs.xlim, abs.xlim)) + 
  geom_label_repel(
    aes(label = gene), 
    size = 3, 
    data = . %>% filter(significant),
    max.overlaps = 20
  )
  return(g)
}

plot.volcano(tregs.tissue.scps.de.genes, 'tregs.tissue.scps')
plot.volcano(tregs.tissue.scps.sat1.de.genes, 'tregs.tissue.scps.sat1')
plot.volcano(tregs.tissue.scps.sat1hi.de.genes, 'tregs.tissue.scps.sat1hi')
plot.volcano(tregs.tissue.scps.sat1lo.de.genes, 'tregs.tissue.scps.sat1lo')
plot.volcano(tregs.tissue.ad.de.genes, 'tregs.tissue.ad')
plot.volcano(tregs.tissue.uc.de.genes, 'tregs.tissue.uc')
plot.volcano(tregs.pbmc.scps.de.genes, 'tregs.pbmc.scps')
plot.volcano(tregs.tissue.sc.de.genes, 'tregs.tissue.sc')
plot.volcano(tregs.tissue.ps.de.genes, 'tregs.tissue.ps')
```

```{r}
write.de.results <- function(de.genes, filename, significant.only) {
  if (significant.only) {
    de.genes <- de.genes %>% subset(subset = significant)
  }
  de.genes %>%
    write.table(
      filename,
      row.names = FALSE,
      quote = FALSE,
      sep = '\t'
    )
}
write.de.results(tregs.tissue.scps.de.genes, '../diffexp/tregs.tissue.scps.de.all.tsv', FALSE)
write.de.results(tregs.tissue.scps.sat1.de.genes, '../diffexp/tregs.tissue.scps.sat1.de.all.tsv', FALSE)
write.de.results(tregs.tissue.scps.sat1hi.de.genes, '../diffexp/tregs.tissue.scps.sat1hi.de.all.tsv', FALSE)
write.de.results(tregs.tissue.scps.sat1lo.de.genes, '../diffexp/tregs.tissue.scps.sat1lo.de.all.tsv', FALSE)
write.de.results(tregs.tissue.uc.de.genes, '../diffexp/tregs.tissue.uc.de.all.tsv', FALSE)
write.de.results(tregs.tissue.ad.de.genes, '../diffexp/tregs.tissue.ad.de.all.tsv', FALSE)
write.de.results(tregs.pbmc.scps.de.genes, '../diffexp/tregs.pbmc.scps.de.all.tsv', FALSE)
write.de.results(tregs.tissue.sc.de.genes, '../diffexp/tregs.tissue.sc.de.all.tsv', FALSE)
write.de.results(tregs.tissue.ps.de.genes, '../diffexp/tregs.tissue.ps.de.all.tsv', FALSE)
write.de.results(tregs.tissue.scps.de.genes, '../diffexp/tregs.tissue.scps.de.signif.tsv', TRUE)
write.de.results(tregs.tissue.scps.sat1.de.genes, '../diffexp/tregs.tissue.scps.sat1.de.signif.tsv', TRUE)
write.de.results(tregs.tissue.scps.sat1hi.de.genes, '../diffexp/tregs.tissue.scps.sat1hi.de.signif.tsv', TRUE)
write.de.results(tregs.tissue.scps.sat1lo.de.genes, '../diffexp/tregs.tissue.scps.sat1lo.de.signif.tsv', TRUE)
write.de.results(tregs.tissue.uc.de.genes, '../diffexp/tregs.tissue.uc.de.signif.tsv', TRUE)
write.de.results(tregs.tissue.ad.de.genes, '../diffexp/tregs.tissue.ad.de.signif.tsv', TRUE)
write.de.results(tregs.pbmc.scps.de.genes, '../diffexp/tregs.pbmc.scps.de.signif.tsv', TRUE)
write.de.results(tregs.tissue.sc.de.genes, '../diffexp/tregs.tissue.sc.de.signif.tsv', TRUE)
write.de.results(tregs.tissue.ps.de.genes, '../diffexp/tregs.tissue.ps.de.signif.tsv', TRUE)
```