import pandas as pd
import h5py
import argparse as ap
import numpy as np

parser = ap.ArgumentParser()
parser.add_argument(
    '-i',
    '--h5',
    required = True,
    help = 'path to the filtered hdf5 file generated by cellranger aggr'
)
parser.add_argument(
    '-c',
    '--csv',
    required = True,
    help = 'path to the aggregation csv used as cellranger aggr input'
)
parser.add_argument(
    '-o',
    '--outputFile',
    required = True,
    help = 'name of the outputfile'
)
args = parser.parse_args()
aggrcsv = pd.read_csv(args.csv)
aggrcsv = aggrcsv.loc[:, aggrcsv.columns != 'molecule_h5']
aggrcsv = aggrcsv.reset_index()
aggrcsv.loc[:, 'index'] = aggrcsv.index + 1
with h5py.File(args.h5, 'r') as h5:
    df = pd.DataFrame(
        {'barcodes': h5['matrix']['barcodes'][:].astype('U')}
    )
    df['index'] = df.barcodes.apply(
        lambda x: int(x.split('-')[-1])
    )
    df = df.merge(
        aggrcsv,
        on = 'index',
        how = 'left'
    )
    df.drop(
        columns = ['index'],
        inplace = True
    )
    df.to_csv(
        args.outputFile,
        sep = '\t',
        index = False
    )
